server:
  port: 8129
spring:
  datasource:
    username: root
    password: "root"
    url: jdbc:mysql://127.0.0.1:3306/patient?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    # URL响应地址（Springboot默认为/**)
    static-path-pattern: /SystemData/**
    web:
      resources:
        # 静态文件地址，保留官方内容后，进行追加
        static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:SystemData
  servlet:
    multipart:
      max-file-size: 251658240
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
